Repository almsam/data-analysis-project-remastered, pull requests merged in 2024-08, with the labels that each got.

#15 Architecture
  part 2 - bars & parade index.ipynb
  part 3 - political allignment.ipynb
  part 4 - geographical strata.ipynb
Labels: enhancement

#22 Part 3
  part 3 - political allignment.ipynb
Labels: documentation, enhancement

#34 Append part 3b
  part 3 - political allignment.ipynb
Labels: bug

#40 Part 3 b
  part 3 - political allignment.ipynb
Labels: documentation, enhancement, in review

#48 Part 4
  part 4 - geographical strata.ipynb
Labels: documentation, enhancement

#51 Part 4b
  images/atlanta.png
  images/austin.png
  images/boston.png
  images/chicago.png
  images/denver.png
  images/houston.png
  images/los-angeles.png
  images/miami.png
  images/new-orleans.png
  images/new-york-adjusted.png
  images/new-york.png
  images/philadelphia.png
  images/portland.png
  images/san-francisco.png
  images/seattle.png
  images/washington-dc.png
  part 4 - geographical strata.ipynb
Labels: enhancement, in review

#64 Create Original Final Tableau Dashboard.jpg
  dashboard/Original Final Tableau Dashboard.jpg
Labels: in review
